import { NextRequest, NextResponse } from 'next/server'

const modelResponses: Record<string, string> = {
  'GPT-4':
    'Based on your prompt, here\'s a comprehensive response leveraging advanced reasoning and knowledge. This response demonstrates deep understanding and provides actionable insights tailored to your specific query.',
  'GPT-3.5 Turbo':
    'Here\'s a quick and efficient response to your prompt. This model balances speed with quality, providing useful information in a concise format.',
  'Claude 3 Opus':
    'This is a thoughtful response that prioritizes accuracy and nuance. Claude excels at detailed analysis and maintaining context throughout complex conversations.',
  'Gemini Pro':
    'Gemini provides a multimodal perspective on your query. This response integrates various types of information processing for a holistic answer.',
  'Llama 2':
    'This open-source model provides a practical response focused on being helpful, harmless, and honest. Llama models are excellent for specialized domains.',
  Qwen:
    'Qwen delivers a response optimized for both English and Chinese processing. This model is particularly strong in multilingual scenarios.',
}

export async function POST(request: NextRequest) {
  try {
    const { prompt, model } = await request.json()

    if (!prompt) {
      return NextResponse.json({ error: 'No prompt provided' }, { status: 400 })
    }

    // Simulate model response
    const modelKey = model || 'GPT-4'
    const baseResponse = modelResponses[modelKey] || modelResponses['GPT-4']

    const response = `${baseResponse}\n\n---\n\nYour Prompt:\n"${prompt}"\n\nThis response was generated by ${modelKey} with estimated token usage and cost calculations shown in the metrics bar below.`

    const tokens = Math.floor(Math.random() * 500) + 100
    const cost = (tokens * 0.00003).toFixed(4)

    return NextResponse.json({
      response,
      tokens,
      cost,
    })
  } catch (error) {
    console.error('Prompt execution error:', error)
    return NextResponse.json({ error: 'Failed to execute prompt' }, { status: 500 })
  }
}
